### PR TITLE
Update bootstrap4.html

### PR DESCRIPTION
**Pull request by ozeranskiy**
Update template breadcrumbs for bootstrap 4 (https://getbootstrap.com/docs/4.0/components/breadcrumb/)

### CODE REVIEW

**Comment by prymitive** [comment]
Thanks, do you mind fixing tests so I can merge this?
[test_render_bs4](https://github.com/prymitive/bootstrap-breadcrumbs/blob/master/tests/test_templatetags.py#L300)
[test_render_empty_url_bs4](https://github.com/prymitive/bootstrap-breadcrumbs/blob/master/tests/test_templatetags.py#L359)

**Comment by prymitive** [comment]
Squashed commits and updated tests, they should be passing now.
Can you double check that it still works for you?

**Comment by prymitive** [comment]
@ozeranskiy are you happy with my update here?

**Comment by ozeranskiy** [comment]
@prymitive yes, tnx

**Comment by prymitive** [comment]
I've just released 0.9.1 with this change

**Comment by ozeranskiy** [comment]
@prymitive nice)

**Pull request merged**
